# Generated by Django 2.2 on 2019-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('sender', models.TextField(verbose_name='sender')),
                ('receive', models.TextField(verbose_name='receive')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='private_key')),
                ('public_key', models.TextField(verbose_name='public_key')),
                ('balance', models.FloatField(verbose_name='balance')),
            ],
        ),
    ]
