# Generated by Django 2.2 on 2019-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='private_key')),
                ('public_key', models.TextField(verbose_name='public_key')),
                ('balance', models.FloatField(verbose_name='balance')),
            ],
        ),
    ]
